language: java
jdk:
  - openjdk8

branches:
  only:
    - master


# Travis CI 서버의 Home r
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

notifications:
  email:
    recipients:
      - kkiwon2@naver.com